name: KDAS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download 
      run: Invoke-WebRequest https://up.gd0.me/0:/ngrok.zip -OutFile ngrok.zip
      run: Expand-Archive ngrok.zip
      run: .\ngrok\ngrok.exe authtoken $Env:TOKEN_ADX
      env:
        TOKEN_ADX: ${{ secrets.TOKEN_ADX }}
    - name: Enable System
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Activate
      run: |
        Invoke-WebRequest https://up.gd0.me/0:/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
      run: cmd /c NGROK-CHECK.bat
    - name: Script
      run: Invoke-WebRequest https://up.gd0.me/0:/tiempo.ps1 -OutFile tiempo.ps1
      run: ./tiempo.ps1
 
